### ISSUE TITLE
[Feature Request] Query by address

### ISSUE THREAD

**Issue by shayanb** [go-faast/faast-portfolio#1]
similar service to ethplorer.io but much nicer view as Faa.st portfolio view is awesome.

e.g: https://ethplorer.io/address/0x2561fd0f1651a6828bafbd41847957fe9b0e0370

**Comment by nathanielwood** [comment]
Good idea, should be pretty straight forward to implement. It should probably be obvious that you're viewing an address (view mode) rather than accessing your portfolio.

**Comment by shayanb** [comment]
@nathanielwood yes, I was thinking to show user the same page as portfolio where when clicked on `modify your portfolio` would show the initial page of the portfolio to import their private key.

**Comment by nathanielwood** [comment]
Completed in commit ef219623

**Comment by shayanb** [comment]
@nathanielwood looks great! thanks
