### ISSUE TITLE
Pending Token Transfers  should be indicated in portfolio

### ISSUE THREAD

**Issue by kenthunt** [go-faast/faast-portfolio#17]
After signing off on the token purchase, the pending allocation should be visible in the portfolio as "pending transfers". While this requires some sort of state management, html5 allows local storage of such information. https://www.w3schools.com/html/html5_webstorage.asp

While this would not be visible cross platforms, it should smooth out the customer confusion about completed transactions awaiting token transfers. The funds are not gone, the order is just being filled...

**Comment by dylanseago** [comment]
Thanks for the issue. This looks to be a duplicate of #2
