### ISSUE TITLE
Invalid JSON RPC response: {}

### ISSUE THREAD

**Issue by rraallvv** [go-faast/faast-portfolio#45]
I can't use the portfolio at faa.st, I get the error `Invalid JSON RPC response: {}` also tried sending a message to support@faa.st but haven't received any response, although this issue is not exclusively related to the source code in repository, there is still a change that it is so I' posting it here nonetheless.

**Comment by dwolfgram** [comment]
thanks for letting us know, i'll let the right people know about your email! I am pretty sure this is something we are looking into/working on fixing right now.

**Comment by dwolfgram** [comment]
Actually, just got word it should be fixed! Let us know if you have any more issues

**Comment by rraallvv** [comment]
@dwolfgram Awesome! Thanks, it's very much appreciated.
