### ISSUE TITLE
View and follow tokens you don't own from the Balances page

### ISSUE THREAD

**Issue by nathanielwood** [go-faast/faast-portfolio#5]
Viewing other tokens and their charts would be very beneficial. Being able to "follow" tokens would require setting a state somewhere. Local storage is used for settings but is not persisted across browsers/devices. Blockstack storage can be a solution but there's a current issue with mixed content (https->http). Server side storage would be another alternative

**Comment by dylanseago** [comment]
Implemented as asset watch list
